version: 0.2

phases:
  install:
    commands:
      # install rust
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
      - source "$HOME/.cargo/env"
  build:
    commands:
      - ls
      # build Rust binary
      - cargo build --release
      # binary name must be "bootstrap" for Lambda custom runtime
      - mv target/release/spotify_extension_lambda bootstrap
      # strip & check size, dependencies
      - strip --strip-all bootstrap
      - size bootstrap
      - ldd bootstrap
      - zip bootstrap.zip bootstrap
      - aws s3 cp bootstrap.zip s3://spotify-extension-src/bootstrap.zip
      - aws lambda update-function-code --function-name arn:aws:lambda:ap-northeast-1:312678712486:function:SpotifyExtension --s3-bucket spotify-extension-src --s3-key bootstrap.zip
