name: Docker Compose CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1
  AWS_ROLE_ARN: arn:aws:iam::312678712486:role/SpotifyExtentionAPI-CD
  S3_BUCKET_NAME: spotify-extension-src
  LAMBDA_FUNCTION_NAME: arn:aws:lambda:ap-northeast-1:312678712486:function:SpotifyExtension

jobs:
  deploy:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: use chahe v3
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

        # Required for docker/build-push-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # なぜか動かない
      #- name: Build and push
      #  uses: docker/build-push-action@v4
      #  with:
      #    context: .
      #    cache-from: type=gha
      #    cache-to: type=gha,mode=max

      - name: Build
        run: |
          ./build_lambda_function_executable.sh

      - name: copy to s3
        run: aws s3 cp bootstrap.zip s3://${{ env.S3_BUCKET_NAME }}

      - name: update lambda function source
        run: |
          aws lambda update-function-code --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --s3-bucket spotify-extension-src --s3-key bootstrap.zip --publish
