# This is a basic workflow to help you get started with Actions

name: upload to s3

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          S3_BACKET_NAME: ${{ secrets.S3_BACKET_NAME }}
          
        run: |
          aws s3 cp --recursive --region ap-northeast-1 . s3://$S3_BACKET_NAME/src/
        
